FROM ubuntu

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y php php-mysql php-curl composer php-dom 
RUN snap install ngrok
RUN composer install

EXPOSE 82
RUN ngrok config add-authtoken 2ZZj21Kee9JkxCgNetS8exKsMfK_86t1rTBnc2TxWWWPqHmkC
RUN ngrok http 82
CMD php -S 0.0.0.0:82 -t public

