<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Client\ApiClient::class => App\Client\ApiClientFactory::class,
            App\Client\HttpClient::class => App\Client\HttpClientFactory::class,
            App\Handle\HttpClient::class => App\Handle\HttpClientFactory::class,
            App\Handler\ApiClient::class => App\Handler\ApiClientFactory::class,
            App\Handler\GetTokenHandler::class => App\Handler\GetTokenHandlerFactory::class,
            App\Handler\HttpClient::class => App\Handler\HttpClientFactory::class,
            App\Handler\RedirectUriHandler::class => App\Handler\RedirectUriHandlerFactory::class,
            App\Handler\SumHandler::class => App\Handler\SumHandlerFactory::class,
        ],
    ],
];
